name: Update packages

on:
# 定时触发  
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started

env:
  # 时区
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    name: Update ${{matrix.target}}
    # 上游目标更新
    strategy:
      fail-fast: false
      matrix:
        target: [18.06,19.07]
        
    steps:
    # 校验本地文件  
    - name: Checkout
      uses: actions/checkout@main
    
    # 初始化编译环境
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    # 下载软件包     
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{matrix.target}}.sh
        git clone -b ${{matrix.target}} https://github.com/kenzok8/small-package.git ${{matrix.target}}
        cd ${{matrix.target}}
        rm -Rf *
        git rm --cache *
        $GITHUB_WORKSPACE/${{matrix.target}}.sh
        
    # 上传到分支
    - name: Upload
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -m "同步上游更新$(TZ='Asia/Shanghai' date +@%m%d%H)"
        git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/kenzok8/small-package.git" HEAD:${{matrix.target}}
